gpus: '0'
workers: 4
name: 'res50_128x96_d256x3_adam_lr1e-3'

dataset:
  name: 'coco'
  root: 'd:/datasets/coco/'
  train_set: 'train2017'
  test_set: 'val2017'
  flip: true
  rot_factor: 40
  scale_factor: 0.3
  half_body_prob: 0
  half_body_num_joints: 8
  color_rgb: false

model:
  name: 'resnet50'
  pretrained: true
  input_width: 96
  input_height: 128
  output_width: 24
  output_height: 32
  sigma: 1
  num_joints: 17
  target_type: 'gaussian'
  mean:
  - 0.485
  - 0.456
  - 0.406
  std:
  - 0.229
  - 0.224
  - 0.225
  extra:
    final_conv_kernel: 1
    deconv_with_bias: false
    num_deconv_layers: 3
    num_deconv_filters:
    - 256
    - 256
    - 256
    num_deconv_kernels:
    - 4
    - 4
    - 4

loss:
  use_target_weight: true

train:
  batch_size: 32
  shuffle: true
  num_epochs: 140
  optimizer: 'adam'
  lr: 1e-3
  lr_factor: 0.1
  lr_step:
  - 90
  - 120

test:
  batch_size: 32
  coco_bbox_file: 'data/coco/person_detection_results/COCO_val2017_detections_AP_H_56_person.json'
  bbox_thr: 1.0
  image_thr: 0.0
  in_vis_thr: 0.2
  model_file: ''
  nms_thr: 1.0
  oks_thr: 0.9
  use_gt_bbox: true
  flip_test: true
  post_process: true
  blur_kernel: 3